#include "helper.h"
#include "visual.h"
#include <stdio.h>

void write_vtkFile( const char *szProblem,int timeStepNumber, int gridsize, int imax, int jmax,
                    double dx, double dy, double *U, double *dt) {
  
	char szFileName[80];
	FILE *fp=NULL;
	sprintf( szFileName, "%s.%i.vtk", szProblem, timeStepNumber );
	fp = fopen( szFileName, "w");
	if( fp == NULL )		       
	{
		char szBuff[80];
		sprintf( szBuff, "Failed to open %s", szFileName );
		ERROR( szBuff );
		return;
	}

	write_vtkHeader( fp, imax, jmax, dx, dy);
	write_vtkPointCoordinates(fp, imax, jmax, dx, dy);
  
	fprintf(fp,"POINT_DATA %i \n", (imax + 1)*(jmax + 1) );
	
    fprintf(fp,"\n");
    fprintf(fp, "VECTORS velocity float\n");
    for(int x = 0; x < jmax + 1; x++) {
        for(int y = 0; y < imax + 1; y++) {
        	// if (x < jmax || y < imax)
        	// {
        	// 	fprintf(fp, "%f %f 0\n", U[(x*gridsize + y)*3 + 1], U[(x*gridsize + y)*3 + 2] ); 
        	// }
        	// else
        	// {
        		fprintf(fp, "0 0 0\n"); 
        	// }
			
        }
    }

	fprintf(fp,"\n");
	fprintf(fp,"CELL_DATA %i \n", imax*jmax );
	fprintf(fp, "SCALARS waterhight float 1 \n"); 
	fprintf(fp, "LOOKUP_TABLE default \n");
	for(int x = 0; x < imax; x++) {
		for(int y = 0; y < jmax; y++) {
			fprintf(fp, "%f\n", U[(x*gridsize + y)*3]);
		}
	}
  fprintf(fp,"\n");
  fprintf(fp, "SCALARS celldt float 1 \n"); 
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(int x = 0; x < imax; x++) {
    for(int y = 0; y < jmax; y++) {
      fprintf(fp, "%f\n", dt[x*gridsize + y]);
    }
  }

	if( fclose(fp) )
	{
		char szBuff[80];
		sprintf( szBuff, "Failed to close %s", szFileName );
		ERROR( szBuff );
	}
}


void write_vtkHeader( FILE *fp, int imax, int jmax, 
                      double dx, double dy) {
  if( fp == NULL )		       
  {
    char szBuff[80];
    sprintf( szBuff, "Null pointer in write_vtkHeader" );
    ERROR( szBuff );
    return;
  }

  fprintf(fp,"# vtk DataFile Version 2.0\n");
  fprintf(fp,"generated by Tsunami-simulation Seminar output (written by Xiao Xue) \n");
  fprintf(fp,"ASCII\n");
  fprintf(fp,"\n");	
  fprintf(fp,"DATASET STRUCTURED_GRID\n");
  fprintf(fp,"DIMENSIONS  %i %i 1 \n", imax + 1, jmax + 1);
  fprintf(fp,"POINTS %i float\n", (imax + 1)*(jmax+1) );
  fprintf(fp,"\n");
}


void write_vtkPointCoordinates( FILE *fp, int imax, int jmax, 
                      double dx, double dy) {
  double originX = 0.0;  
  double originY = 0.0;

  int i = 0;
  int j = 0;

  for(j = 0; j < jmax + 1; j++) {
    for(i = 0; i < imax + 1; i++) {
      fprintf(fp, "%f %f 0\n", originX+(i*dx), originY+(j*dy) );
    }
  }
}